### PR TITLE
updated

### PR DESCRIPTION
**Pull request by ogunleye0720**
I have edited the send_mailer.php file which
has been sent to your email. I have ensured client-side validation  in the file. I have also edited the contact_form.php file. In the contact.php file, I have restructured the loading class, error-message class, and the sent-message css class. I wrapped all three classes inside a <div class = "form-group"></div> element. I also edited the custom.css file, from line 896 to line 989. This is to ensure proper styling which fixed the bugs on the form-validation. I also edited the validate.js jquery code to manipulate the form-validation.

### CODE REVIEW

**Comment by tiwiex** [comment]
Thanks. I also notice a new file in form folder called contact.php. Is this file required or it just ended up un the git commit? Am I replacing my contact_form.php with contact.php?

**Comment by ogunleye0720** [comment]
Hello sir,
Ignore the file sir. I used it as a blueprint.

Sent from Yahoo Mail on Android 
 
  On Thu, Jul 13, 2023 at 7:31 AM, Taiwo ***@***.***> wrote:   


Thanks. I also notice a new file in form folder called contact.php. Is this file required or it just ended up un the git commit? Am I replacing my contact_form.php with contact.php?

**Review by tiwiex — APPROVED** [review]
Ok. Let me merge and pull

**Comment by tiwiex** [comment]
I have merged and pulled. However, i see no changes. I suggest you do a pull of the master branch and see if you get the changes. Thanks.

**Comment by ogunleye0720** [comment]
- <!DOCTYPE html>  
   - <html>  
   - <head>  
   - <style>  
   - .error {color: #FF0001;}  
   - </style>  
   - </head>  
   - <body>    
   -   
   - <?php  
   - // define variables to empty values  
   - $nameErr = $emailErr = $mobilenoErr = $genderErr = $websiteErr = $agreeErr = "";  
   - $name = $email = $mobileno = $gender = $website = $agree = "";  
   -   
   - //Input fields validation  
   - if ($_SERVER["REQUEST_METHOD"] == "POST") {  
   -       
   - //String Validation  
   -     if (emptyempty($_POST["name"])) {  
   -          $nameErr = "Name is required";  
   -     } else {  
   -         $name = input_data($_POST["name"]);  
   -             // check if name only contains letters and whitespace  
   -             if (!preg_match("/^[a-zA-Z ]*$/",$name)) {  
   -                 $nameErr = "Only alphabets and white space are allowed";  
   -             }  
   -     }  
   -       
   -     //Email Validation   
   -     if (emptyempty($_POST["email"])) {  
   -             $emailErr = "Email is required";  
   -     } else {  
   -             $email = input_data($_POST["email"]);  
   -             // check that the e-mail address is well-formed  
   -             if (!filter_var($email, FILTER_VALIDATE_EMAIL)) {  
   -                 $emailErr = "Invalid email format";  
   -             }  
   -      }  
   -     
   -     //Number Validation  
   -     if (emptyempty($_POST["mobileno"])) {  
   -             $mobilenoErr = "Mobile no is required";  
   -     } else {  
   -             $mobileno = input_data($_POST["mobileno"]);  
   -             // check if mobile no is well-formed  
   -             if (!preg_match ("/^[0-9]*$/", $mobileno) ) {  
   -             $mobilenoErr = "Only numeric value is allowed.";  
   -             }  
   -         //check mobile no length should not be less and greator than 10  
   -         if (strlen ($mobileno) != 10) {  
   -             $mobilenoErr = "Mobile no must contain 10 digits.";  
   -             }  
   -     }  
   -       
   -     //URL Validation      
   -     if (emptyempty($_POST["website"])) {  
   -         $website = "";  
   -     } else {  
   -             $website = input_data($_POST["website"]);  
   -             // check if URL address syntax is valid  
   -             if (!preg_match("/\b(?:(?:https?|ftp):\/\/|www\.)[-a-z0-9+&@#\/%?=~_|!:,.;]*[-a-z0-9+&@#\/%=~_|]/i",$website)) {  
   -                 $websiteErr = "Invalid URL";  
   -             }      
   -     }  
   -       
   -     //Empty Field Validation  
   -     if (emptyempty ($_POST["gender"])) {  
   -             $genderErr = "Gender is required";  
   -     } else {  
   -             $gender = input_data($_POST["gender"]);  
   -     }  
   -   
   -     //Checkbox Validation  
   -     if (!isset($_POST['agree'])){  
   -             $agreeErr = "Accept terms of services before submit.";  
   -     } else {  
   -             $agree = input_data($_POST["agree"]);  
   -     }  
   - }  
   - function input_data($data) {  
   -   $data = trim($data);  
   -   $data = stripslashes($data);  
   -   $data = htmlspecialchars($data);  
   -   return $data;  
   - }  
   - ?>  
   -   
   - <h2>Registration Form</h2>  
   - <span class = "error">* required field </span>  
   - <br><br>  
   - <form method="post" action="<?php echo htmlspecialchars($_SERVER["PHP_SELF"]); ?>" >    
   -     Name:   
   -     <input type="text" name="name">  
   -     <span class="error">* <?php echo $nameErr; ?> </span>  
   -     <br><br>  
   -     E-mail:   
   -     <input type="text" name="email">  
   -     <span class="error">* <?php echo $emailErr; ?> </span>  
   -     <br><br>  
   -     Mobile No:   
   -     <input type="text" name="mobileno">  
   -     <span class="error">* <?php echo $mobilenoErr; ?> </span>  
   -     <br><br>  
   -     Website:   
   -     <input type="text" name="website">  
   -     <span class="error"><?php echo $websiteErr; ?> </span>  
   -     <br><br>  
   -     Gender:  
   -     <input type="radio" name="gender" value="male"> Male  
   -     <input type="radio" name="gender" value="female"> Female  
   -     <input type="radio" name="gender" value="other"> Other  
   -     <span class="error">* <?php echo $genderErr; ?> </span>  
   -     <br><br>  
   -     Agree to Terms of Service:  
   -     <input type="checkbox" name="agree">  
   -     <span class="error">* <?php echo $agreeErr; ?> </span>  
   -     <br><br>                            
   -     <input type="submit" name="submit" value="Submit">   
   -     <br><br>                             
   - </form>  
   -   
   - <?php  
   -     if(isset($_POST['submit'])) {  
   -     if($nameErr == "" && $emailErr == "" && $mobilenoErr == "" && $genderErr == "" && $websiteErr == "" && $agreeErr == "") {  
   -         echo "<h3 color = #FF0001> <b>You have sucessfully registered.</b> </h3>";  
   -         echo "<h2>Your Input:</h2>";  
   -         echo "Name: " .$name;  
   -         echo "<br>";  
   -         echo "Email: " .$email;  
   -         echo "<br>";  
   -         echo "Mobile No: " .$mobileno;  
   -         echo "<br>";  
   -         echo "Website: " .$website;  
   -         echo "<br>";  
   -         echo "Gender: " .$gender;  
   -     } else {  
   -         echo "<h3> <b>You didn't filled up the form correctly.</b> </h3>";  
   -     }  
   -     }  
   - ?>  
   -   
   - </body>  
   - </html>  

When the above code runs on a browser, the output will be like the screenshot below:


    On Thursday, July 13, 2023 at 09:04:32 AM GMT+1, Taiwo Akinosho ***@***.***> wrote:  
 
 


Merged #1 into master.

**Pull request merged**
